baseURL = 'Ki6j.com'
languageCode = 'en-us'
title = 'KI6J'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Projects'
  url = '/Projects'
  weight = 2
[[menu.main]]
  name = 'Library'
  url = '/Library'
  weight = 3  
[[menu.main]]
  name = 'Contact'
  url = '/Contact'
  weight = 4

relativeURLs = false
